- alias: Alarm sounds on pending

  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: pending

  action:
    - service: media_player.volume_set
      data:
        volume_level: 0.2
      target:
        entity_id:
          - media_player.sonos_arc
          # - media_player.kitchen_google_nest_mini

    - service: media_player.repeat_set
      data:
        repeat: all
      target:
        entity_id:
          - media_player.sonos_arc
          # - media_player.kitchen_google_nest_mini

    - service: media_player.play_media
      data:
        entity_id:
          - media_player.sonos_arc
          # - media_player.kitchen_google_nest_mini
        media_content_id: !secret pending_alarm_sound_location
        media_content_type: music
