- alias: Reset alarm when disarmed

  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed

  action:
    - service: notify.notify
      data:
        message: "[ALARM] The alarm is Disarmed at {{ states('sensor.date_time') }}"

    - service: media_player.media_stop
      target:
        entity_id:
          - media_player.sonos_arc
          # - media_player.kitchen_google_nest_mini
