- alias: "Make Hue Dimmer great again"

  variables:
    command: "{{ trigger.event.data.command }}"
    args: "{{ trigger.event.data.args }}"

  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: !secret hue_dimmer_kitchen_device_id

  action:
    - choose:
        - conditions: "{{ command == 'on_press' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness: 150
                rgb_color: [255, 166, 5]

        - conditions: "{{ command == 'on_double_press' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness: 150
                effect: colorloop

        - conditions: "{{ command == 'on_triple_press' }}"
          sequence:
            - service: pyscript.toggle_hue_dimmer_spotify

        - conditions: "{{ command == 'off_with_effect' }}"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.zha_lights_downstairs
              data:
                transition: 0.4

        # Dimmer buttons
        - conditions:
            - "{{ command == 'step' }}"
            - "{{ args == [0, 30, 9] }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness_step_pct: 10
                transition: 1

        - conditions:
            - "{{ command == 'step' }}"
            - "{{ args == [0, 56, 9] }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness_step_pct: 25
                transition: 1

        - conditions:
            - "{{ command == 'step' }}"
            - "{{ args == [1, 30, 9] }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness_step_pct: -10
                transition: 1

        - conditions:
            - "{{ command == 'step' }}"
            - "{{ args == [1, 56, 9] }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.zha_lights_downstairs
              data:
                brightness_step_pct: -25
                transition: 1
