- alias: Turn on the light in the toilet when motion is detected.

  variables:
    no_motion_wait: 120

  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion_sensor_occupancy
      to: "on"

  mode: restart

  action:
    - service: light.turn_on
      target:
        entity_id: light.toilet_led_level_light_color_on_off
      # data:
      # brightness: 107
      # color_temp: 399

    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.toilet_motion_sensor_occupancy
        from: "on"
        to: "off"

    - delay: "{{ no_motion_wait }}"

    - service: light.turn_off
      target:
        entity_id: light.toilet_led_level_light_color_on_off
