- alias: Livingroom Lights On
  trigger:
    platform: state
    entity_id: sun.sun
    to: "below_horizon"
  action:
    service: light.turn_on
    target:
      entity_id: light.zha_lights_downstairs

- alias: Downstairs Lights Off - Weekdays
  trigger:
    platform: state
    entity_id: sensor.time
    to: "22:15"
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  action:
    service: light.turn_off
    target:
      entity_id: light.zha_lights_downstairs
